### ISSUE TITLE
Map Pop-up Button to Side Mouse Button

### ISSUE THREAD

**Issue by comtomru** [max-kamps/jpd-breader#37]
I'd like to map the jpdb-reader pop-up button to a side mouse button for convenient access but can't find any instructions on how to do this. Is this feature available, and if so, how can I achieve this? If not, please consider adding it for improved user experience. Thanks!

**Comment by max-kamps** [comment]
Just added this in 1adbd1b
My mouse does not have side buttons, so I can't test it myself. It also seems like buttons mouse3 and mouse4 might be unavailable because they are used as browser back/forward buttons.
