### ISSUE TITLE
(Unknown part of speech #va, please report) for 死ぬ

### ISSUE THREAD

**Issue by mdraves91** [max-kamps/jpd-breader#66]
Got this error for [死ぬ](https://jpdb.io/vocabulary/1310730/%E6%AD%BB%E3%81%AC/%E3%81%97%E3%81%AC).
I'm guessing va is verb-archaic. 

This is what it parsed as: `Intransitive Verb, (Unknown part of speech #va, please report), Godan Verb, ぬ Godan Verb`
This is what jpdb.io shows: `Verb (archaic, intransitive) Verb (5-dan, ぬ, intransitive)`

**Comment by max-kamps** [comment]
This is resolved on master already, but the fix has not been included in any release.
I'll try to get a release put together today.

**Comment by mdraves91** [comment]
no need to rush on my account, just wanted to make sure you knew about it since it said 'please report' 🙂
